export enum ActivityAction {
  // Workspace Actions
  WORKSPACE_CREATED = 'WORKSPACE_CREATED',
  WORKSPACE_UPDATED = 'WORKSPACE_UPDATED',
  WORKSPACE_DELETED = 'WORKSPACE_DELETED',
  MEMBER_INVITED = 'MEMBER_INVITED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  MEMBER_LEFT = 'MEMBER_LEFT',
  ROLE_UPDATED = 'ROLE_UPDATED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
  INVITATION_SENT = 'INVITATION_SENT',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  INVITATION_DECLINED = 'INVITATION_DECLINED',
  INVITATION_CANCELLED = 'INVITATION_CANCELLED',

  // Project Actions
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_ARCHIVED = 'PROJECT_ARCHIVED',
  PROJECT_RESTORED = 'PROJECT_RESTORED',
  PROJECT_DELETED = 'PROJECT_DELETED',

  // Board Actions
  BOARD_CREATED = 'BOARD_CREATED',
  BOARD_UPDATED = 'BOARD_UPDATED',
  BOARD_DELETED = 'BOARD_DELETED',

  // Column Actions
  COLUMN_CREATED = 'COLUMN_CREATED',
  COLUMN_UPDATED = 'COLUMN_UPDATED',
  COLUMN_DELETED = 'COLUMN_DELETED',
  COLUMN_REORDERED = 'COLUMN_REORDERED',

  // Task Actions
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_MOVED = 'TASK_MOVED',
  TASK_DELETED = 'TASK_DELETED',
  TASK_RESTORED = 'TASK_RESTORED',

  // Comment Actions
  COMMENT_CREATED = 'COMMENT_CREATED',
  COMMENT_UPDATED = 'COMMENT_UPDATED',
  COMMENT_DELETED = 'COMMENT_DELETED',
  COMMENT_REACTION_ADDED = 'COMMENT_REACTION_ADDED',
  COMMENT_REACTION_REMOVED = 'COMMENT_REACTION_REMOVED',

  // Attachment Actions
  ATTACHMENT_UPLOADED = 'ATTACHMENT_UPLOADED',
  ATTACHMENT_DELETED = 'ATTACHMENT_DELETED',

  // Task Link Actions
  TASK_LINK_CREATED = 'TASK_LINK_CREATED',
  TASK_LINK_UPDATED = 'TASK_LINK_UPDATED',
  TASK_LINK_DELETED = 'TASK_LINK_DELETED',

  // Checklist Actions
  CHECKLIST_ITEM_CREATED = 'CHECKLIST_ITEM_CREATED',
  CHECKLIST_ITEM_TOGGLED = 'CHECKLIST_ITEM_TOGGLED',
  CHECKLIST_ITEM_UPDATED = 'CHECKLIST_ITEM_UPDATED',
  CHECKLIST_ITEM_DELETED = 'CHECKLIST_ITEM_DELETED',

  // Label Actions
  LABEL_CREATED = 'LABEL_CREATED',
  LABEL_UPDATED = 'LABEL_UPDATED',
  LABEL_DELETED = 'LABEL_DELETED',
  LABEL_ATTACHED = 'LABEL_ATTACHED',
  LABEL_DETACHED = 'LABEL_DETACHED',

  // Sprint Actions
  SPRINT_CREATED = 'SPRINT_CREATED',
  SPRINT_UPDATED = 'SPRINT_UPDATED',
  SPRINT_STARTED = 'SPRINT_STARTED',
  SPRINT_COMPLETED = 'SPRINT_COMPLETED',
  SPRINT_DELETED = 'SPRINT_DELETED',
  TASK_MOVED_TO_SPRINT = 'TASK_MOVED_TO_SPRINT',

  // Bulk Actions
  TASKS_BULK_UPDATED = 'TASKS_BULK_UPDATED',
  TASKS_BULK_DELETED = 'TASKS_BULK_DELETED',
}
