export enum ActivityAction {
  WORKSPACE_CREATED = 'WORKSPACE_CREATED',
  MEMBER_INVITED = 'MEMBER_INVITED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  OWNERSHIP_TRANSFERRED = 'OWNERSHIP_TRANSFERRED',
}
